
[/Script/Engine.RendererSettings]
r.Mobile.UseMobileUniformLocalLights=True
r.UseEmulatedUniformBuffers=True

[SystemSettings]
vr.PixelDensity=1

; 開 / 關 rendering features
r.MotionBlurQuality=0
r.BloomQuality=1
r.EyeAdaptationQuality=0
r.LensFlareQuality=0
r.SceneColorFringeQuality=0
r.FastBlurThreshold=0



; Texture / Filtering
r.MaxAnisotropy=4

; Quality groups
sg.EffectsQuality=1
sg.PostProcessQuality=0
